### ISSUE TITLE
SharePoint 2016 support - RTM, FP2

### ISSUE THREAD

**Issue by NZainchkovskiy** [SubPointSolutions/metabox#2]
Do you have any planned release date for SP2016 support? I think it's most interesting version for new deployments.

**Comment by avishnyakov** [comment]
Hey @NZainchkovskiy, thanks for raising this up.

It is in a roadmap, a few weeks to go. Most of the infrastructure is already setup. In fact, here is what we have for win2016 stack:
* dc setup
* sql 12/14 setup
* domain joins
* SharePoint 2016 RTM media downloads
* even SharePoint 2016 farm provision with DSC

However, a major issue has to do with IIS sites being provisioned wrongly which caused SharePoint 2016 farm being down. Aren't sure why this happens, something has to do with doubled up certificates on IIS side. Suspect that either it's due to incorrect pre-req installs or SharePoint RTM distributive. We'll give it a go on non-RTM distro soon and see how it would go.

Meanwhile, we put together tons of doco on internals, on how it all works, and fully documented win2-12-r2 stack which you might found interesting. Consider this as a "getting started" guide which won't be any different to win2016 stack at all:

metabox guides - win2012 r2
> https://github.com/SubPointSolutions/metabox/wiki/metabox-guides-win2012-r2

**Comment by avishnyakov** [comment]
@NZainchkovskiy, good news. We've got the following stack implemented on Windows 2016:
* Win2016 + DC
* Win2016 + SQL 14
* Win2016 + SharePoint 2016 RTM
* Win2016 + SharePoint 2016 Feature Pack 2

That coves exactly what you were after providing ~20 minutes turnaround for a SharePoint 2016 farm created from scratch assuming DC/SQL is there already. If not, then DC/SQL is ~15-20 minutes each built from scratch.

Publishing branch and running regression tomorrow. Once done, will document win2016 stack similar way we did 2012.
