### ISSUE TITLE
Implement built-in Azure support 

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#23]
As a metabox user, I want to be able to spin up infrastructure in Azure same way as we do locally, on the laptops. Metabox should be able to work with Azure with minimal changes in YAML configuration and CLI.

Leaving it here, looking for the community help on initial design, ideas, use cases and implementation. The very much idea is to support easy builds of the SharePoint farms in Azure: eliminate low-level routines of building initial images and infrastructure so that we can focus on important things rather than fighting issues or manually running/troubleshooting scripts. Moving forward, we'll follow up with AWS as much as we can.

This is one of the goals of the metabox design: not only provide a high-level abstraction for local infrastructure builds but to support cloud-based environments to a reasonable extent. Locally, it is possible with Packer/Vagrant tools, and for cloud-based environments, it is possible with Packer/Terraform/Vagrant. 

With the current state of the things, we are ready to start moving forward: there are working win12/16 stacks with SharePoint 2013/2016, there is a QA process under continuous integration with Jenkins2 pipelines. That frees up resources and holds QA so that we can safely enhance metabox API with Azure support.

Here is a rough idea of how it may work:

* [ ] plan Azure topology and Azure resources (what are they? - resource groups, storage accounts, network, VMs and so on) 
* [ ] investigate `terraform` tool, most likely, we will be using `terraform` to bootstrap and handle Azure related resource provision for initial Packer build and further VM provision
* [ ] investigate metabox changes to be done to support Azure scenario (packer images, terraform support to drive provision instead of Vagrant, new parameters and CLI changes)
* [ ] implement metabox feature to support Azure scenario
* [ ] implement regression testing, new Jenkins2 pipelines

**Comment by shurick81** [comment]
Ok, let's see what we should take into consideration with Azure (and maybe in with cloud in general).
1. Organizing cloud resources into manageable units, so called 'resource groups'. They can be used for delegating permissions, for cost calculation and similar administrative purposes. So we need to decide how we use them in Metabox. One option is to create a separate resource group for each machine stack. Another way is to use one resource group for all the resources and stacks. It might be wise to not have mandatory separation by resource groups because in some cases it will be useful to have more than one stack in one resource group.
- for one is the case when we need to run multiple stacks in one project environment. For example, the project of upgrade from one SP version to another.
- another case is when company policy regulates using resource groups and for example one developer is only supplied with one resource group for all the resources. That is quite logical considering the nature of the Azure resource groups.

2. Resource location (geographically) should be handled properly so that entire deployment workflow takes place in one datacenter. <to be elaborated>
3. vm images are stored in so called 'storage accounts'. <to be elaborated>
4. file resources handling is to be discussed in #42.

**Comment by shurick81** [comment]
When it comes to resource locations, again, the most important is that for the sake of speed we need to use the same location for all the resources: file resources, images, virtual machines. There is some silly restriction to keep in mind: CPU limit in one location per one subscription. MS applies some soft CPU limitations. For example, here is how it looks for my subscription in Ireland datacenter:

```
PS C:\WINDOWS\system32> Get-AzureRmVMUsage -Location "Northeurope"

Name                             Current Value Limit  Unit
----                             ------------- -----  ----
...
Total Regional vCPUs                        17    20 Count
...
```

The conclusion might be that we need to allow creating machines in different locations just to overcome this limit.
More details: https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits

**Comment by shurick81** [comment]
With regard to locating VM images, we need to consider either using VHD or managed images. In SPConfstructor I used managed images that abstracts the file nature of the images so that I can just use resource name and image name to refer to any image. However, to make the solution more generic and less specific to Azure, it can be sensible to use more traditional file-like image. What is the approach in AWS?

**Comment by shurick81** [comment]
As for the authentication, using SPN seems be the only feasible option because we need unattended workflows. In this case we will have to handle access keys somehow. Should we store them in the code? Should we use Vault or similar tools?

**Comment by SubPointSupport** [comment]
Tracking outside of GitHub, closing here.
