### ISSUE TITLE
Azure support for file resources

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#42]
Follow up on the Azure support ticket:
> Implement built-in Azure support #23

Currently, metabox can save file resources on the local file system. Azure support needs to be done so that packer/vagrant would be able to pull files from the Azure.

**Comment by shurick81** [comment]
I understand that you might have expected a solution from me but let me first put a dilemma instead.
### Intro
Let's distinguish following objects on this topology:
* Initial Source: where the files are initially located. Can be Internet public resource or private/enterprise file storage.
* Consumer: computing node, VM that uses files from Local Source.
* Local Source: storage where the file is temporary saved for caching or processing.
* Downloader: computing node that is performing the downloading from the Initial Source to Local Source.
* Metabox: computing node where Metabox API is running.

With this in mind we have following constraints:
* Local Source should be as much as possible close to Consumer so that the latter can download files very quickly.
* Downloader should be as much as possible transparent and have broad connection to both Initial Source and Local Source. The poorest of these two channels will be a bottle neck in the process.

### Local hypervisors
When we deal with some local hypervisor like VirtualBox, it is reasonable that Local Source should be located on the same host or in the same local network with Consumer and it is the same machine where Downloader code is running.

### Cloud resources
Similarly when it comes to clouds, Local Source should be located very close, somewhere in the same datacenter with Consumer. In case with Azure the Local Source can be a file share or blobs that are quickly accessible from Azure VMs. The dilemma then is where Downloader should be run. Currently we are running it as a part of the Metabox manager, on the host where Metabox API is running. It seems however that the best would be to have it running in the same datacenter with Local Source. It can be a VM or a container for running this load in Azure. This will make downloading much faster, especially for Azure because Initial Source is also located somewhere in Microsoft datacenters. Until it is implemented this way in MB, developers will suffer if they have poor Internet connection.

With regard to the Local Source implementation in Azure, a file share is much easier for connecting to directly from VM with such common protocols like smb, http, etc. Here is the difference in more detail: https://docs.microsoft.com/en-us/azure/storage/common/storage-decide-blobs-files-disks

**Comment by shurick81** [comment]
There is also another option for making downloading faster in Azure: we can recommend that users run Metabox API on the Azure VM (and later I hope we can containerize it somehow) and then the whole Metabox, including Downloader, will be running inside Azure datacenter. An additional benefit from this is that the flow will be not dependent on connection between user's desktop and Azure datacenter. So users with poor or unstable connection will benefit a lot. It is also more mobile ready solution.

Consider this scenario: I committed new revision, then I pull it on some machine in Azure and call Metabox API, say, to build new packages and machines. Then I close my developer's laptop and go to the park, and I can open my laptop in one hour and check the logs the result.

It is also connected to our plans of using Jenkins or other software to orchestrate the flow.

**Comment by SubPointSupport** [comment]
Tracking outside of GitHub, closing here.
