### ISSUE TITLE
Random RDP failures due to May 2018 security update

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/metabox#76]
A bunch of metabox built VMs aren't available via RDP. Seems to be caused by May 2018 security update.

> Starting in the May 2018 Security update we are enforcing the March 2018 CVE-2018-0886.

* https://blogs.technet.microsoft.com/yongrhee/2018/05/09/after-may-2018-security-update-rdp-an-authentication-error-occurred-this-could-be-due-to-credssp-encryption-oracle-remediation/
*  https://blogs.technet.microsoft.com/askpfeplat/2018/05/07/credssp-rdp-and-raven/

**Comment by SubPointSupport** [comment]
Rebuilding SOEs with the recent win16 updates fixes this. Both client and server need to have the recent updates.

**Comment by shurick81** [comment]
It seems like updates are not installed in SOE, I will test more thoroughly a bit later.
![image](https://user-images.githubusercontent.com/11289124/41426371-adc2be50-7003-11e8-9fba-b575cdbff7f4.png)

**Comment by shurick81** [comment]
Steps to reproduce from https://github.com/SubPointSolutions/metabox/commit/aeebdf9c02c06103e5222eb55642d2dee96c4800

1. cd to `src`.
2. prepare at least soe and app images
3. create the machine
4. try to open in RDP, authenticate

Expected result: domain controller is open via RDP.

Outcome:
![image](https://user-images.githubusercontent.com/11289124/41585434-5a364d06-73aa-11e8-84f0-0a51fde2240a.png)

Additional info: in Windows installed updates there is only KB3192137 installed, so no May updates are installed:

![image](https://user-images.githubusercontent.com/11289124/41585997-f2b3d1ce-73ab-11e8-8c3f-aea2a9e6c842.png)

The reason I can observe at the time is that Get-WUInstall does not manage to install updates, it only starts installation, reports the list of updates to install and then returns the focus to console. But Windows update service has no time to install because provisioning restarts the machine.

I am now working on the workaround, a provisioning that installs the particular May update, https://github.com/SubPointSolutions/metabox/tree/fix/%2376. However, we need to think if any other updates still should be installed in SOE.

**Comment by shurick81** [comment]
@avishnyakov, what Windows updates do we need in images? Should it be some specific updates listed in our code or should it be just the latest CU on the moment of building SOE image?

**Comment by shurick81** [comment]
I think we need to specify the list in the code to make more stable and determined configuration.

**Comment by shurick81** [comment]
Created a PR for a quick fix: https://github.com/SubPointSolutions/metabox/pull/89

**Comment by avishnyakov** [comment]
@shurick81  just had a look, we need to move this patch into file resource and then reuse it to aavoid downloads.

**Comment by shurick81** [comment]
Agree, we need this. Another approach can be using later Windows builds. For example, update for 1803 build will only weigh about 300M as far as I remember.

**Comment by shurick81** [comment]
Here is the command to list all the updates currently installed:
```
get-wmiobject -class win32_quickfixengineering
```

**Comment by shurick81** [comment]
Additionally found this script for installing latest Windows updates in Packer environment: https://github.com/hashicorp/best-practices/blob/master/packer/scripts/windows/install_windows_updates.ps1

**Comment by avishnyakov** [comment]
@shurick81, this script fetches PSWindowsUpdate and then does pretty much similar thing which we do in packer templates. 

Closing this task, fixes in integration branch as a part of the following ticket:
> metabox fails to build win2016-mb-soe image #96
